// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import "time"

type Atleta struct {
	ID                  int64
	Nombre              string
	MetodologiaObjetivo string
	Peso                float64
	CoachID             int64
}

type Certificacion struct {
	ID           int64
	EntrenadorID int64
	Nombre       string
	Institucion  string
	FechaEmision time.Time
}

type CicloEntrenamiento struct {
	ID          int64
	AtletaID    int64
	Estado      string
	FechaInicio time.Time
}

type Entrenador struct {
	ID              int64
	Nombre          string
	Especialidad    string
	CapacidadMaxima int64
	CargaActual     float64
}

type EvaluacionCiclo struct {
	ID                   int64
	CicloEntrenamientoID int64
	NivelFatiga          int64
	Comentarios          string
	FechaEvaluacion      time.Time
}

type HorarioAtencion struct {
	ID           int64
	EntrenadorID int64
	DiaSemana    string
	HoraInicio   string
	HoraFin      string
}

type Lesion struct {
	ID          int64
	AtletaID    int64
	Descripcion string
	Gravedad    string
	Estado      string
}

type MetricaFisica struct {
	ID              int64
	AtletaID        int64
	PorcentajeGrasa float64
	MasaMuscular    float64
	FechaMedicion   time.Time
}

type Microciclo struct {
	ID                   int64
	CicloEntrenamientoID int64
	NumeroSemana         int64
	EnfoqueEspecifico    string
	FechaInicio          time.Time
}
