// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"
)

// =========================================================
// EvaluacionCiclo
// =========================================================
// ===================== ACTUALIZAR =====================

const actualizarEvaluacionCiclo = `-- name: ActualizarEvaluacionCiclo :one
UPDATE evaluacionCiclo
SET cicloEntrenamientoID = ?, nivelFatiga = ?, comentarios = ?, fechaEvaluacion = ?
WHERE id = ?
RETURNING id, cicloEntrenamientoID, nivelFatiga, comentarios, fechaEvaluacion
`

type ActualizarEvaluacionCicloParams struct {
	ID                   int64
	CicloEntrenamientoID int64
	NivelFatiga          int64
	Comentarios          string
	FechaEvaluacion      time.Time
}

func (q *Queries) ActualizarEvaluacionCiclo(ctx context.Context, arg ActualizarEvaluacionCicloParams) (EvaluacionCiclo, error) {
	row := q.db.QueryRowContext(ctx, actualizarEvaluacionCiclo,
		arg.CicloEntrenamientoID,
		arg.NivelFatiga,
		arg.Comentarios,
		arg.FechaEvaluacion,
		arg.ID)
	var i EvaluacionCiclo
	err := row.Scan(
		&i.ID,
		&i.CicloEntrenamientoID,
		&i.NivelFatiga,
		&i.Comentarios,
		&i.FechaEvaluacion,
	)
	return i, err
}

// ===================== BORRAR =====================

const borrarEvaluacionCiclo = `-- name: BorrarEvaluacionCiclo :execrows
DELETE FROM evaluacionCiclo WHERE id = ?
`

func (q *Queries) BorrarEvaluacionCiclo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarEvaluacionCiclo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// ===================== BUSCAR =====================

const buscarEvaluacionCicloPorID = `-- name: BuscarEvaluacionCicloPorID :one
SELECT id, cicloEntrenamientoID, nivelFatiga, comentarios, fechaEvaluacion FROM evaluacionCiclo
WHERE id = ?
`

func (q *Queries) BuscarEvaluacionCicloPorID(ctx context.Context, id int64) (EvaluacionCiclo, error) {
	row := q.db.QueryRowContext(ctx, buscarEvaluacionCicloPorID, id)
	var i EvaluacionCiclo
	err := row.Scan(
		&i.ID,
		&i.CicloEntrenamientoID,
		&i.NivelFatiga,
		&i.Comentarios,
		&i.FechaEvaluacion,
	)
	return i, err
}

// ===================== CREAR =====================

const crearEvaluacionCiclo = `-- name: CrearEvaluacionCiclo :one
INSERT INTO evaluacionCiclo (evaluacionCiclo, nivelFatiga, comentarios, fechaEvaluacion)
VALUES (?, ?, ?, ?)
RETURNING id, evaluacionCiclo, nivelFatiga, comentarios, fechaEvaluacion
`

type CrearEvaluacionCicloParams struct {
	CicloEntrenamientoID int64
	NivelFatiga          int64
	Comentarios          string
	FechaEvaluacion      time.Time
}

func (q *Queries) CrearEvaluacionCiclo(ctx context.Context, arg CrearEvaluacionCicloParams) (EvaluacionCiclo, error) {
	row := q.db.QueryRowContext(ctx, crearEvaluacionCiclo,
		arg.CicloEntrenamientoID,
		arg.NivelFatiga,
		arg.Comentarios,
		arg.FechaEvaluacion,
	)
	var i EvaluacionCiclo
	err := row.Scan(
		&i.ID,
		&i.CicloEntrenamientoID,
		&i.NivelFatiga,
		&i.Comentarios,
		&i.FechaEvaluacion,
	)
	return i, err
}

// ===================== LISTAR =====================

const listarEvaluacionCiclo = `-- name: ListarEvaluacionCiclo :many
SELECT id, evaluacionCiclo, nivelFatiga, comentarios, fechaEvaluacion FROM evaluacionCiclo
`

func (q *Queries) ListarEvaluacionCiclo(ctx context.Context) ([]EvaluacionCiclo, error) {
	rows, err := q.db.QueryContext(ctx, listarEvaluacionCiclo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvaluacionCiclo
	for rows.Next() {
		var i EvaluacionCiclo
		if err := rows.Scan(&i.ID,
			&i.CicloEntrenamientoID,
			&i.NivelFatiga,
			&i.Comentarios,
			&i.FechaEvaluacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// =========================================================
// CicloEntrenamiento
// =========================================================
// ===================== ACTUALIZAR =====================

const actualizarCicloEntrenamiento = `-- name: ActualizarCicloEntrenamiento :one
UPDATE cicloEntrenamiento
SET atletaID = ?, estado = ?, fechaInicio = ?
WHERE id = ?
RETURNING id, atletaID, estado, fechaInicio
`

type ActualizarCicloEntrenamientoParams struct {
	AtletaID    int64
	Estado      string
	FechaInicio time.Time
	ID          int64
}

func (q *Queries) ActualizarCicloEntrenamiento(ctx context.Context, arg ActualizarCicloEntrenamientoParams) (CicloEntrenamiento, error) {
	row := q.db.QueryRowContext(ctx, actualizarCicloEntrenamiento,
		arg.AtletaID,
		arg.Estado,
		arg.FechaInicio,
		arg.ID)
	var i CicloEntrenamiento
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.Estado,
		&i.FechaInicio,
	)
	return i, err
}

// ===================== BORRAR =====================

const borrarCiclo = `-- name: BorrarCicloEntrenamiento :execrows
DELETE FROM cicloEntrenamiento WHERE id = ?
`

func (q *Queries) BorrarCiclo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarCiclo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// ===================== BUSCAR =====================

const buscarCicloPorID = `-- name: BuscarCicloPorID :one
SELECT id, atletaID, estado, fechaInicio FROM cicloEntrenamiento
WHERE id = ?
`

func (q *Queries) BuscarCicloPorID(ctx context.Context, id int64) (CicloEntrenamiento, error) {
	row := q.db.QueryRowContext(ctx, buscarCicloPorID, id)
	var i CicloEntrenamiento
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.Estado,
		&i.FechaInicio,
	)
	return i, err
}

// ===================== CREAR =====================

const crearCicloEntrenamiento = `-- name: CrearCicloEntrenamiento :one
INSERT INTO cicloEntrenamiento (atletaID, estado, fechaInicio)
VALUES (?, ?, ?)
RETURNING id, atletaID, estado, fechaInicio
`

type CrearCicloEntrenamientoParams struct {
	AtletaID    int64
	Estado      string
	FechaInicio time.Time
}

func (q *Queries) CrearCicloEntrenamiento(ctx context.Context, arg CrearCicloEntrenamientoParams) (CicloEntrenamiento, error) {
	row := q.db.QueryRowContext(ctx, crearCicloEntrenamiento,
		arg.AtletaID,
		arg.Estado,
		arg.FechaInicio,
	)
	var i CicloEntrenamiento
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.Estado,
		&i.FechaInicio,
	)
	return i, err
}

// ===================== LISTAR =====================

const listarCiclos = `-- name: ListarCiclos :many
SELECT id, atletaID, estado, fechaInicio FROM cicloEntrenamiento
`

func (q *Queries) ListarCiclos(ctx context.Context) ([]CicloEntrenamiento, error) {
	rows, err := q.db.QueryContext(ctx, listarCiclos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CicloEntrenamiento
	for rows.Next() {
		var i CicloEntrenamiento
		if err := rows.Scan(&i.ID,
			&i.AtletaID,
			&i.Estado,
			&i.FechaInicio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// =========================================================
// Microciclo
// =========================================================
// ===================== ACTUALIZAR =====================

const actualizarMicrociclo = `-- name: ActualizarMicrociclo :one
UPDATE microciclo
SET cicloEntrenamientoID = ?, numeroSemana = ?, enfoqueEspecifico = ?, fechaInicio = ?
WHERE id = ?
RETURNING id, cicloEntrenamientoID, numeroSemana, enfoqueEspecifico, fechaInicio
`

type ActualizarMicrocicloParams struct {
	ID                   int64
	CicloEntrenamientoID int64
	NumeroSemana         int64
	EnfoqueEspecifico    string
	FechaInicio          time.Time
}

func (q *Queries) ActualizarMicrociclo(ctx context.Context, arg ActualizarMicrocicloParams) (Microciclo, error) {
	row := q.db.QueryRowContext(ctx, actualizarMicrociclo,
		arg.CicloEntrenamientoID,
		arg.NumeroSemana,
		arg.EnfoqueEspecifico,
		arg.FechaInicio,
		arg.ID,
	)
	var i Microciclo
	err := row.Scan(
		&i.ID,
		&i.CicloEntrenamientoID,
		&i.NumeroSemana,
		&i.EnfoqueEspecifico,
		&i.FechaInicio,
	)
	return i, err
}

// ===================== BORRAR =====================

const borrarMicrociclo = `-- name: BorrarMicrociclo :execrows
DELETE FROM microciclo WHERE id = ?
`

func (q *Queries) BorrarMicrociclo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarMicrociclo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// ===================== BUSCAR =====================

const buscarMicrocicloPorID = `-- name: BuscarMicrocicloPorID :one
SELECT id, cicloEntrenamientoID, numeroSemana, enfoqueEspecifico, fechaInicio FROM microciclo
WHERE id = ?
`

func (q *Queries) BuscarMicrocicloPorID(ctx context.Context, id int64) (Microciclo, error) {
	row := q.db.QueryRowContext(ctx, buscarMicrocicloPorID, id)
	var i Microciclo
	err := row.Scan(
		&i.ID,
		&i.CicloEntrenamientoID,
		&i.NumeroSemana,
		&i.EnfoqueEspecifico,
		&i.FechaInicio,
	)
	return i, err
}

// ===================== CREAR =====================

const crearMicrociclo = `-- name: CrearMicrociclo :one
INSERT INTO microciclo (cicloEntrenamientoID, numeroSemana, enfoqueEspecifico, fechaInicio)
VALUES (?, ?, ?, ?)
RETURNING id, cicloEntrenamientoID, numeroSemana, enfoqueEspecifico, fechaInicio
`

type CrearMicrocicloParams struct {
	CicloEntrenamientoID int64
	NumeroSemana         int64
	EnfoqueEspecifico    string
	FechaInicio          time.Time
}

func (q *Queries) CrearMicrociclo(ctx context.Context, arg CrearMicrocicloParams) (Microciclo, error) {
	row := q.db.QueryRowContext(ctx, crearMicrociclo,
		arg.CicloEntrenamientoID,
		arg.NumeroSemana,
		arg.EnfoqueEspecifico,
		arg.FechaInicio,
	)
	var i Microciclo
	err := row.Scan(
		&i.ID,
		&i.CicloEntrenamientoID,
		&i.NumeroSemana,
		&i.EnfoqueEspecifico,
		&i.FechaInicio,
	)
	return i, err
}

// ===================== LISTAR =====================

const listarMicrociclo = `-- name: ListarMicrociclo :many
SELECT id, cicloEntrenamientoID, numeroSemana, enfoqueEspecifico, fechaInicio FROM microciclo
`

func (q *Queries) ListarMicrociclo(ctx context.Context) ([]Microciclo, error) {
	rows, err := q.db.QueryContext(ctx, listarMicrociclo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Microciclo
	for rows.Next() {
		var i Microciclo
		if err := rows.Scan(
			&i.ID,
			&i.CicloEntrenamientoID,
			&i.NumeroSemana,
			&i.EnfoqueEspecifico,
			&i.FechaInicio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
